name: cinema
description: "Travaux pratiques INFO 2"
publish_to: 'none'
version: 0.2025.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  shimmer: ^3.0.0
  dart_phonetics: ^1.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

assets:
  - profile.jpg
  - flags/
