name: cinema
description: "Travaux pratiques "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  shimmer: ^3.0.0
  dart_phonetics: ^1.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - profile.jpg
  - flags/
